### ISSUE TITLE
silence #null automatically at start

### ISSUE THREAD

**Issue by alexcoder04** [alexcoder04/if-schleife-bot#21]

**Comment by CuzImClicks** [comment]
Aber dafür ist doch das silenced.json ding da, oder funktioniert das noch nicht?

**Comment by alexcoder04** [comment]
Ja, aber:
1. Ist es sinnvoll, die ChannelID auf GitHub zu veröffentlichen (ja, der läuft eh nur auf unseren DC Server, aber ist eine Bad Practice).
2. Wenn nicht auf Github pushen, dann funktioniert es nicht, da Heroku das Repo bei jedem Update neu klont und packaged

**Comment by CuzImClicks** [comment]
ja das ist aber egal weil wir den bot ja wahrscheinlich/hoffentlich auf dem schulserver hosten können
